server:
  port: 8000

spring:
  application:
    name: 'post-service'
  datasource:
    url: ${DB_URL:jdbc:postgresql://104.154.113.225:5432/postgres}
    username: ${DB_USERNAME:postgres}
    password:  ${DB_PASSWORD:password123}
    driver-class-name: org.postgresql.Driver

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI}
angular:
  uri: ${ANGULAR_URI}


validationServer: ${VALIDATION}

management:
  endpoints:
    web:
      exposure:
        include: "health,info,metrics,prometheus"