apiVersion: v1
kind: Service
metadata:
  name: sonarqube008-service
  namespace: sonarqube
spec:
  selector:
    app: sonarqube-sonarqube
  type: LoadBalancer
  ports:
    - port: 9000
      targetPort: 9000
