#-------deployment and services grouped together here in one file
#-------deployment----------
apiVersion: apps/v1
kind: Deployment
#-------metadate and specs----------
metadata:
  name: mongo-deployment
  labels:
    app: nenaMongo
spec:
  replicas: 1
  #-------selector----------defines which pods belong to this deployment
  selector:
    matchLabels:
      app: nenaMongo
  template:
  #-------metadate and specs----------each pod gets a unique name, however they share the same label
    metadata:
      labels:
        app: nenaMongo
    spec:
      containers:
      #-------Containers--------------------lookup the desired image on dockerhub or any repository
      #-------based on the image, find out the port it usually runs on from documentation
      #-------based on the database type, find out the username and pass variables from documentation
      #-------then you need to pass environment variables in this configuration file
      #-------reference Secret data from the mongo-secret.yaml file
      - name: mongodb
        image: mongo:5.0
        ports:
        - containerPort: 27017
        env:
        - name:  MONGO_INITDB_ROOT_USERNAME
          valueFrom:
             secretKeyRef:
                name:   mongo-secret
                key:   mongo-user
        - name:  MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
             secretKeyRef:
                name:   mongo-secret
                key:   mongo-password
---
#---------service INTERNAL----------
apiVersion: v1
kind: Service
metadata:
  name: mymongo-service
spec:
  type: ClusterIP
  selector:
    app: nenaMongo
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 27017
#-------------the ports for the pod and the service targetPort must match
#-------------the host port 8080 could be anything, it could even match the pod and service port
#https://www.youtube.com/watch?v=s_o8dwzRlu4