---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: project3-angular-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: angular-deployment
  template:
    metadata:
      labels:
        app: angular-deployment
    spec:
      containers:
      - image: project2team4/angular:latest
        env:
          - name: GATEWAY_URI
            value: http://35.223.254.189:8084
          - name: EMAIL_URL
            value: http://34.135.244.116:8079
        imagePullPolicy: Always
        name: angularcontainer
        ports: 
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: angular-service
  name: angular
  namespace: default
spec:
  type: LoadBalancer
  ports:
    - name: http-angular
      port: 80
      targetPort: 80
  selector:
    app: angular-deployment









