---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: project3-gateway-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gateway-deployment
  template:
    metadata:
      labels:
        app: gateway-deployment
    spec:
      containers:
      - image: project2team4/gateway:latest
        env:
          - name: EUREKA_URI
            value: http://35.239.70.25:8083/eureka
          - name: ANGULAR_URI
            value: http://34.69.17.73:80
          - name: USER_URI
            value:
        imagePullPolicy: Always
        name: gatewaycontainer
        ports: 
        - containerPort: 8084

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: gateway-service
  name: gateway
  namespace: default
spec:
  type: LoadBalancer
  ports:
    - name: http-app1
      port: 8084
      targetPort: 8084
  selector:
    app: gateway-deployment






